pipeline {
    agent any
    stages {
        stage("Sprawdz_lokalne_istnienie_Composera") {
            steps {
			    bat 'php C:\\xampp7_3\\php\\composer.phar --version'
            }
        }
        stage("Uzyj_lokalnego_Composera") {
            steps {
                bat 'cd www && php C:\\xampp7_3\\php\\composer.phar install'
            }
        }		
        stage("W podkatalogu www uruchomienie PHP bez autoloadera") {
            steps {
                bat 'cd www && php skrypt-bez-autoload.php'
            }
        }
		stage("W podkatalogu www uruchomienie PHP z autoloaderem") {
            steps {
                bat 'cd www && php index.php'
            }
        }
		stage("W podkatalogu www uruchomienie PHPUnit") {
            steps {
                bat 'cd www && php ./vendor/phpunit/phpunit/phpunit ./tests'
            }
        }
    }
}
