pipeline {
    agent any
    stages {
        stage("Sprawdz_istnienie_Composera") {
            steps {
			    bat 'php C:\\xampp7_3\\php\\composer.phar --version'
                //bat 'cd www && composer install'
            }
        }
        stage("W podkatalogu www uruchomienie PHP bez autoloadera") {
            steps {
                bat 'cd www && dir && php skrypt-bez-autoload.php'
            }
        }
    }
}
